### ISSUE TITLE
No current speed, energy consumption, power and max speed are displayed

### ISSUE THREAD

**Issue by fbsoftware-stuttgart** [Sublimis/UrbanBiker#147]
Hello,

since latest release (v6.10), current speed isn't displayed anymore... It shows always 0. 

Energy consumption current Power and max speed also aren't calculated anymore. 

Distance and average speed are calculated and displayed correctly.

My Device:
Samsung A8 (Samsung SM-A530F), Android 9

**Comment by Sublimis** [comment]
Hi, can you please try with the newest beta version? You can get it from https://play.google.com/apps/testing/com.sublimis.urbanbiker. If you can, please let us know how it went. We think this should be fixed now, but we are unable to replicate the exact issue to be certain. Sorry for the inconvenience, and thanks for the feedback!

**Comment by fbsoftware-stuttgart** [comment]
Hi, i won't ride my bike before Monday. 

Monday evening i can give you feedback if the beta (v6.11) fixed it for me.

**Comment by Sublimis** [comment]
A new beta version has been released, v6.11 dated 2021-10-19. We have changed our GPS speed processing algorithm completely, so are optimistic this should finally work. Please let us know, if you find the time to test it. Thank you!

**Comment by fbsoftware-stuttgart** [comment]
nope, v6.11 dated 2021-10-19 didn't fix it either. At the beginning of the recording it goes up to 3.2 km/h and stays there for a few seconds before it falls down to 0. 

And later it went up to 4.0 km/h for a few seconds before it fell down to 0 again.

My guess is, there happens a division by zero or some other exception is thrown...

**Comment by Sublimis** [comment]
Thank you! Quality of the GnssLogger app is sub-par, not really useful. Instead, we found [Geo Tracker](https://play.google.com/store/apps/details?id=com.ilyabogdanovich.geotracker) app with the required feature. Take a look at the lower-left corner of the screenshots, note the speed and speed accuracy value after the ± sign that are always shown. If you're curious enough, you can use this to easily observe your speed accuracy 🙂
