### ISSUE TITLE
Split screen: not switching to landscape?

### ISSUE THREAD

**Issue by Scooty66** [Sublimis/UrbanBiker#52]
Hi there,

preferably using Urban Biker in split screen mode together with Locus Maps.
Working fine with  Android 9 and MIUI 10.3.3 on my Mi Mix 2S.
Just updated to Android 10 and MIUI 11.0.3 and Urban Biker and now it looks like this:
![Screenshot_2020-02-08-14-37-58-028_com sublimis urbanbiker](https://user-images.githubusercontent.com/5012764/74086369-81aca280-4a82-11ea-88d7-984b4c4b14a9.jpg)

So to me it looks like being still in portrait mode showing each meter in a separate line and a quite small speed dial.
Formerly in split screen it switched to landscape mode with three meters in two lines and a big speed dial. Much better to read in landscape mode (to get an impression you may look at the second screenshot in [issue 34](https://github.com/Sublimis/UrbanBiker/issues/34)).
Manually changing to landscape mode through "Menu/Control Panel" while in split screen does still show portrait mode.

Anything else I can try to get landscape mode in split screen?
If you need further information/tests please let me know.

Thanks for any hint,
Andreas

**Comment by Sublimis** [comment]
Hi Andreas, we've fixed this and will publish a new beta today. As far as Android is concerned, this works exactly as expected, so there's nothing you can do in the current version v5.52 to make it work as described. Android is simply ignoring any screen orientation requests from apps in split screen mode, and instead puts them into the orientation which it deems most suitable. So we had to implement a kind of workaround to force it to work, but it seems to be working just fine.

One thing you can try immediately, though, is to resize the window by using the handlebar between two apps (try to make Urban Biker window more wide than tall), or to rotate the screen with the sensor. The chances are slim, though.

In any case, the new beta will arrive today so please let us know how it went.

**Comment by Scooty66** [comment]
Using version 5.53 (is this version the beta?) landscape is now shown in split screen when setting it manually through "Menu/Control Panel". So that way I am back to the display I use most.

In "Auto orientation" it still shows portrait mode, even if split screen window is sized more wide than tall.
But that does not matter, manually setting landscape as standard is absolutely fine with me.

Thanks a lot for your support.

Andreas
